version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: [ ]
    schedule:
      interval: monthly
      time: '17:00'
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    labels: [ ]
    schedule:
      interval: monthly
      time: '17:00'
    ignore:
      - dependency-name: '*'
        update-types: 
          - version-update:semver-major
    groups:
      npm-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
